### ISSUE TITLE
Starcheck doesn't detect SM74 on Coop DX

### ISSUE THREAD

**Issue by lKomus** [andre1048576/StarCheck#10]
Using coopdx 1.0.1. Somehow the mod doesn't detect sm74 and asks to use the default layout despite a layout seemingly available for it?
![image](https://github.com/user-attachments/assets/141e67e6-6b9f-43e7-80a7-c1fe929734b9)

**Comment by andre1048576** [comment]
The file name for sm74 was updated recently, so now StarCheck will detect the new filename
Thanks for the bug report!
